import argparse
import sys
from pathlib import Path

from mod_online_update import OnlineUpdateMoD
from mod_build_all import AllBuildMoD
from mod_build_interval import IntervalBuildMoD
from data_loader import DataLoader


def get_args():
    parser = argparse.ArgumentParser(description='group_simulator')
    parser.add_argument(
        "--build-type",
        type=str,
        default="online",
        help="The type of build to perform. Options: 'online', 'all', 'interval'. Default: 'online'."
    )
    parser.add_argument(
        "--data-dir",
        type=str,
        default="dataset/madama/split_data_random",
        help="Directory containing MADAMA *_train.csv files generated by prepare_madama.py."
    )
    try:
        args = parser.parse_args()
    except:
        parser.print_help()
        sys.exit(0)

    return args


def create_builder(build_type):
    if build_type == "online":
        return OnlineUpdateMoD(
            config_file="config_madama.yaml",
            current_cliff=None,
            output_cliff_folder=f"cliffmaps/madama/{build_type}",
            save_fig_folder=f"save_fig_{build_type}")

    if build_type == "all":
        return AllBuildMoD(
            config_file="config_madama.yaml",
            current_cliff=None,
            output_cliff_folder=f"cliffmaps/madama/{build_type}",
            save_fig_folder=f"save_fig_{build_type}",
            build_type=build_type)

    if build_type == "interval":
        return IntervalBuildMoD(
            config_file="config_madama.yaml",
            current_cliff=None,
            output_cliff_folder=f"cliffmaps/madama/{build_type}",
            save_fig_folder=f"save_fig_{build_type}",
            build_type=build_type)

    raise ValueError(f"Unsupported build type: {build_type}")


if __name__ == "__main__":
    args = get_args()
    train_files = sorted(Path(args.data_dir).glob("*_train.csv"))
    if not train_files:
        raise FileNotFoundError(
            f"No MADAMA train split files found in {args.data_dir}. "
            "Run: python3 prepare_madama.py"
        )

    buildMoD = create_builder(args.build_type)

    for train_file in train_files:
        data_loader = DataLoader('config_madama.yaml', raw_data_file=str(train_file))
        observed_traj = data_loader.get_observed_traj_all_area_all_time()
        output_name = train_file.name.removesuffix("_train.csv")
        buildMoD.updateMoD(observed_traj, output_name)
